//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceAnalyzer.Analyzers.CSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PerformanceAnalyzer.Analyzers.CSharp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ArrayPool.
        /// </summary>
        internal static string ArrayDescription {
            get {
                return ResourceManager.GetString("ArrayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ArrayPool.
        /// </summary>
        internal static string ArrayMessageFormat {
            get {
                return ResourceManager.GetString("ArrayMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ArrayPool.
        /// </summary>
        internal static string ArrayTitle {
            get {
                return ResourceManager.GetString("ArrayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamics decrease performance.
        /// </summary>
        internal static string DynamicUsageDescription {
            get {
                return ResourceManager.GetString("DynamicUsageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamics decrease performance.
        /// </summary>
        internal static string DynamicUsageMessageFormat {
            get {
                return ResourceManager.GetString("DynamicUsageMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamics decrease performance.
        /// </summary>
        internal static string DynamicUsageTitle {
            get {
                return ResourceManager.GetString("DynamicUsageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.Empty has a bad JIT optimization (see https://github.com/dotnet/runtime/issues/42694).
        /// </summary>
        internal static string EmptyStringDescription {
            get {
                return ResourceManager.GetString("EmptyStringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer &quot;&quot; over string.Empty.
        /// </summary>
        internal static string EmptyStringMessageFormat {
            get {
                return ResourceManager.GetString("EmptyStringMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer &quot;&quot; over string.Empty.
        /// </summary>
        internal static string EmptyStringTitle {
            get {
                return ResourceManager.GetString("EmptyStringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use compile-time evaluated Enum.ToString() equivalent (nameof).
        /// </summary>
        internal static string EnumNameDescription {
            get {
                return ResourceManager.GetString("EnumNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Enum.ToString().
        /// </summary>
        internal static string EnumNameMessageFormat {
            get {
                return ResourceManager.GetString("EnumNameMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Enum.ToString().
        /// </summary>
        internal static string EnumNameTitle {
            get {
                return ResourceManager.GetString("EnumNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sealing classes may increase performance.
        /// </summary>
        internal static string SealClassesDescription {
            get {
                return ResourceManager.GetString("SealClassesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sealing classes may increase performance.
        /// </summary>
        internal static string SealClassesMessageFormat {
            get {
                return ResourceManager.GetString("SealClassesMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seal class.
        /// </summary>
        internal static string SealClassesTitle {
            get {
                return ResourceManager.GetString("SealClassesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer sizeof(T) to Unsafe.SizeOf&lt;T&gt;.
        /// </summary>
        internal static string SizeOfDescription {
            get {
                return ResourceManager.GetString("SizeOfDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer sizeof(T) to Unsafe.SizeOf&lt;T&gt;.
        /// </summary>
        internal static string SizeOfMessageFormat {
            get {
                return ResourceManager.GetString("SizeOfMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer sizeof(T) to Unsafe.SizeOf&lt;T&gt;.
        /// </summary>
        internal static string SizeOfTitle {
            get {
                return ResourceManager.GetString("SizeOfTitle", resourceCulture);
            }
        }
    }
}
