name: Upload dotnet package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          source-url: https://nuget.pkg.github.com/deeprobin/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build --configuration Release
      - name: Create the package
        run: dotnet pack --configuration Release
      - name: Publish the package to GPR (PerformanceAnalyzer)
        run: dotnet nuget push src/PerformanceAnalyzer/bin/Release/*.nupkg
      - name: Publish the package to GPR (PerformanceAnalyzer.CodeFixes)
        run: dotnet nuget push src/PerformanceAnalyzer.CodeFixes/bin/Release/*.nupkg
      - name: Publish the package to GPR (PerformanceAnalyzer.Package)
        run: dotnet nuget push src/PerformanceAnalyzer.Package/bin/Release/*.nupkg
      - name: Publish the package to GPR (PerformanceAnalyzer.Vsix)
        run: dotnet nuget push src/PerformanceAnalyzer.Vsix/bin/Release/*.nupkg